"""initial schema

Revision ID: b75a353d3036
Revises: 
Create Date: 2026-07-29 04:48:21.640099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b75a353d3036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_validated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('scope_validation', 'reconnaissance', 'scan', 'approval_pending', 'exploitation', 'reporting', 'closed', name='engagementstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('pentester', 'reader', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reports',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('pdf_ref', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('web', 'active_directory', name='targettype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('automatic', 'approval', 'forbidden', name='risktier'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'blocked', 'awaiting_approval', 'running', 'completed', 'failed', name='actionstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('option_chosen', sa.Enum('conservative', 'aggressive', name='approvaloption'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('evidence',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='findingseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('evidence')
    op.drop_table('approvals')
    op.drop_table('actions')
    op.drop_table('targets')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('engagements')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
